name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

jobs:
  terraform-apply:
    name: Terraform Apply
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Configure Snowflake credentials
        run: |
          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: ./snowflake_terraform
        run: terraform init

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ./snowflake_terraform

      - name: Download State File
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: ./snowflake_terraform

      - name: Terraform Apply
        working-directory: ./snowflake_terraform
        run: terraform apply -auto-approve tfplan
      - name: Upload Updated State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: ./snowflake_terraform/terraform.tfstate